### PR TITLE
update CI workflow

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR:
* gives a minor update to the CI workflow
* unpins the `matplotlib` requirement

The goal of this PR is to get CI green again with the current matrix. In subsequent PRs we can prune down OS runs, then see about getting testing up and running for Python 3.11. However, `numba` is still not in available for 3.11 so that is another hurdle.

### CODE REVIEW

**Comment by knaaptime** [comment]
thanks for taking a look. On the mpl front, i think the blocker is [proplot](https://github.com/proplot-dev/proplot/issues/390). Unpinning mpl will pass because we're not currently testing the plotting funcs, which should also change.

On one hand, I think the  proplot fix is probably straightforward, so i'll take a look and see if i can send a PR the dev will merge, but taking a look at the issues/history, its not clear the project will be maintained much, so might also be time to refactor and remove. I like proplots aesthetics and it makes some stuff a lot easier, but its not absolutely critical

**Comment by knaaptime** [comment]
if/until we decide to refactor proplot out, we need to keep the matlotlib pin (because the pinning is done incorrectly in proplot)

**Comment by jGaboardi** [comment]
@knaaptime This is now fixed in `geosnap`, correct? We can close if so.

**Comment by knaaptime** [comment]
yeah, i made proplot optional while its in flux, which was a bit easier than i thought (but will make it a bit harder to make nice figs).

you probably got a billion emails today as i figured this out, but one thing i had to do differently here than the pysal stack is use [`coverage run -m pytest`](https://github.com/oturns/geosnap/blob/a67b45fcd479579b4cc5dd815cbe12b176df7a22/.github/workflows/unittests.yml#L49) otherwise it would refuse to see any lines as run (despite all the tests running through)

**Pull request closed without merging**
