### PR TITLE
setup.py --> pyproject.toml

### PR DESCRIPTION
**Pull request by knaaptime**
- swap to platformdirs
- use pyproject

### CODE REVIEW

**Comment by jGaboardi** [comment]
You'll always have to [update `geosnap/__init__.py`](https://github.com/oturns/geosnap/blob/2e4587cf60e3298fdf7b414a07303192714657d1/geosnap/__init__.py#L35-L36) when swapping out `versioneer` for `setup tools_scm`. See example in [`spopt/__init__.py`](https://github.com/pysal/spopt/blob/main/spopt/__init__.py).

**Comment by jGaboardi** [comment]
Are theCI failures expected?

**Comment by knaaptime** [comment]
yeah i think so. The 3.10s are all known and the windows machines are just running outta memory cause ive sent too many prs today

**Review by jGaboardi — APPROVED** [review]
LGTM

**Pull request merged**
